# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=80, verbose_name='ID')),
                ('created_time', models.DateTimeField(verbose_name='Created Time')),
                ('from_name', models.CharField(max_length=80, verbose_name='Name')),
                ('permalink', models.URLField(max_length=255, verbose_name='Post URL')),
                ('message', models.TextField()),
                ('likes', models.IntegerField()),
                ('comments', models.IntegerField()),
            ],
            options={
                'ordering': ['-likes', 'from_name'],
                'verbose_name_plural': 'Posts',
                'verbose_name': 'Post',
            },
        ),
    ]
